<<<<<<<< .../%MOD_FOLDER%/inlined_BG0114.baf
////////////////////////////////////////////////////////////
// Door0805 trigger destination script
////////////////////////////////////////////////////////////
IF
    Global("BG0114_entered","%NBaldursGate%",1) // from area
THEN
    RESPONSE #100
	TriggerActivation("bggo_BG0200",1)
	TriggerActivation("bggo_BG0300",0)
	SetGlobal("BG0114_entered","%NEBaldursGate%",0)
END

IF
    Global("BG0114_entered","%NEBaldursGate%",1)
THEN
    RESPONSE #100
	TriggerActivation("bggo_BG0200",0)
	TriggerActivation("bggo_BG0300",1)
	SetGlobal("BG0114_entered","%NBaldursGate%",0)
END
>>>>>>>> 

ACTION_IF FILE_EXISTS_IN_GAME ~%are2%.bcs~ BEGIN
	EXTEND_BOTTOM ~%are2%.bcs~ ~.../%MOD_FOLDER%/inlined_BG0114.baf~ EVAL
		
END ELSE BEGIN
	COPY ~.../%MOD_FOLDER%/inlined_BG0114.baf~ ~%workspace%/bif/temp/%are2%.baf~
	COMPILE EVAL ~%workspace%/bif/temp/%are2%.baf~
END
	