<<<<<<<< .../%MOD_FOLDER%/inlined_BG0300_top.baf
IF
	Global("Trigger_deactivate","%NEBaldursGate%",0)
THEN
	RESPONSE #100
		TriggerActivation("Trigger Point 17",FALSE)
		SetGlobal("Trigger_deactivate","%NEBaldursGate%",1)
		SetGlobal("BG0300_Closed_Dr0114b","BG0300",1)
		SetGlobal("BG0300_opened_Dr0114b","BG0300",0)
		SetGlobal("BG0300_unlocked_Dr0114b","BG0300",0)
		SetGlobal("BG0300_text_Dr0114b","BG0300",1)
		SetGlobal("BG0300_change_state_Dr0114b","BG0300",0)
		Continue()
END
>>>>>>>>
EXTEND_TOP ~%are2%.bcs~ ~.../%MOD_FOLDER%/inlined_BG0300_top.baf~ EVAL


<<<<<<<< .../%MOD_FOLDER%/inlined_dr0114b3_script.baf
IF
    Unlocked([ANYONE])
	Global("BG0300_unlocked_Dr0114b","BG0300",0)
THEN
    RESPONSE #100
		SetGlobal("BG0300_unlocked_Dr0114b","BG0300",1)
		SetGlobal("BG0300_text_Dr0114b","BG0300",0)
END

IF
	Clicked([ANYONE])
    OpenState("Dr0114b",TRUE)
	Global("BG0300_unlocked_Dr0114b","BG0300",1)
//    Opened([ANYONE])
THEN
    RESPONSE #100
		SetGlobal("BG0300_Closed_Dr0114b","BG0300",0)
		SetGlobal("BG0300_opened_Dr0114b","BG0300",1)
		SetGlobal("BG0300_change_state_Dr0114b","BG0300",1)
END

IF
	Clicked([ANYONE])
    OpenState("Dr0114b",FALSE)
	Global("BG0300_unlocked_Dr0114b","BG0300",1)
//	Closed([ANYONE])
THEN
    RESPONSE #100
		SetGlobal("BG0300_Closed_Dr0114b","BG0300",1)
		SetGlobal("BG0300_opened_Dr0114b","BG0300",0)
		SetGlobal("BG0300_change_state_Dr0114b","BG0300",1)
END

IF
	Clicked([ANYONE])
	OpenState("Dr0114b",FALSE)
	Global("BG0300_text_Dr0114b","BG0300",1)
	Global("BG0300_unlocked_Dr0114b","BG0300",0)
THEN
	RESPONSE #100
		DisplayString("Dr0114b",211022)
END
>>>>>>>>
COPY ~.../%MOD_FOLDER%/inlined_dr0114b3_script.baf~ ~%workspace%/bif/temp/dr0114b3.baf~
COMPILE ~%workspace%/bif/temp/dr0114b3.baf~ EVAL


<<<<<<<< .../%MOD_FOLDER%/inlined_BG0300.baf
IF
	Global("BG0200_unlocked_Dr0114b","BG0200",1)
THEN
    RESPONSE #100
		Unlock("Dr0114b")
		SetGlobal("BG0300_unlocked_Dr0114b","BG0300",1)
		SetGlobal("BG0300_text_Dr0114b","BG0300",0)
		Continue()
END

IF
	Global("BG0200_Closed_Dr0114b","BG0200",1)
	Global("BG0200_opened_Dr0114b","BG0200",0)
THEN
	RESPONSE #100
	CloseDoor("dr0114b")
	SetGlobal("BG0300_Closed_Dr0114b","BG0300",1)
	SetGlobal("BG0300_opened_Dr0114b","BG0300",0)
	Continue()
END
IF
	Global("BG0200_Closed_Dr0114b","BG0200",0)
	Global("BG0200_opened_Dr0114b","BG0200",1)
THEN
	RESPONSE #100
	OpenDoor("dr0114b")
	SetGlobal("BG0300_Closed_Dr0114b","BG0300",0)
	SetGlobal("BG0300_opened_Dr0114b","BG0300",1)
	Continue()
END

IF
	Global("BG0300_Closed_Dr0114b","BG0300",1)
	Global("BG0300_opened_Dr0114b","BG0300",0)
	Global("BG0300_change_state_Dr0114b","BG0300",1)
THEN
	RESPONSE #100
	CloseDoor("dr0114b")
	SetGlobal("BG0200_Closed_Dr0114b","BG0200",1)
	SetGlobal("BG0200_opened_Dr0114b","BG0200",0)
	SetGlobal("BG0300_change_state_Dr0114b","BG0300",0)
	Continue()
END
IF
	Global("BG0300_Closed_Dr0114b","BG0300",0)
	Global("BG0300_opened_Dr0114b","BG0300",1)
	Global("BG0300_change_state_Dr0114b","BG0300",1)
THEN
	RESPONSE #100
	OpenDoor("dr0114b")
	SetGlobal("BG0200_Closed_Dr0114b","BG0200",0)
	SetGlobal("BG0200_opened_Dr0114b","BG0200",1)
	SetGlobal("BG0300_change_state_Dr0114b","BG0300",0)
	Continue()
END
>>>>>>>>
EXTEND_BOTTOM ~%are2%.bcs~ ~.../%MOD_FOLDER%/inlined_BG0300.baf~ EVAL

/*
<<<<<<<< .../%MOD_FOLDER%/inlined_dr0114b3_script.baf
IF
    Unlocked([ANYONE])
THEN
    RESPONSE #100
		SetGlobal("BG0300_unlocked_Dr0114b","BG0300",1)
END
>>>>>>>>
COPY ~.../%MOD_FOLDER%/inlined_dr0114b3_script.baf~ ~%workspace%/bif/temp/dr0114b3.baf~
COMPILE ~%workspace%/bif/temp/dr0114b3.baf~ EVAL


<<<<<<<< .../%MOD_FOLDER%/inlined_BG0300.baf
IF
	Global("BG0200_unlocked_Dr0114b","BG0200",1)
THEN
    RESPONSE #100
		Unlock("Dr0114b")
//		SetGlobal("BG0200_unlocked_Dr0114b","BG0200",2)
END

IF
//	Global("BG0300_open_dr0114b","BG0300",0)
	OpenState("dr0114b",TRUE)
THEN
    RESPONSE #100
		SetGlobal("BG0300_open_dr0114b","BG0300",1)
		Continue()
END
IF
//	Global("BG0300_open_dr0114b","BG0300",1)
	OpenState("dr0114b",FALSE)
THEN
    RESPONSE #100
		SetGlobal("BG0300_open_dr0114b","BG0300",0)
		Continue()
END

IF
	Global("BG0200_open_dr0114b","BG0200",0)
THEN
	RESPONSE #100
	CloseDoor("dr0114b")
	Continue()
END
IF
	Global("BG0200_open_dr0114b","BG0200",1)
THEN
	RESPONSE #100
	OpenDoor("dr0114b")
	Continue()
END
>>>>>>>>
EXTEND_BOTTOM ~%are2%.bcs~ ~.../%MOD_FOLDER%/inlined_BG0300.baf~ EVAL
*/

/*
<<<<<<<< .../%MOD_FOLDER%/inlined_BG0300.baf
IF
	Global("BG0114_unlocked","%NEBaldursGate%",0)
THEN
	RESPONSE #100
	Unlock("%BG0300_baf_dr0114b%")
	OpenDoor("%BG0300_baf_dr0114b%")
	SetGlobalTimer("Dr0114b_close","%NEBaldursGate%","TEN_ROUNDS")
	Continue()
END
IF 
	Global("BG0114_unlocked","%NEBaldursGate%",0)
	GlobalTimerExpired("Dr0114b_close","%NEBaldursGate%")
THEN
	RESPONSE #100
	CloseDoor("%BG0300_baf_dr0114b%")
	Lock("%BG0300_baf_dr0114b%")
	SetGlobal("BG0114_unlocked","%NEBaldursGate%",1)
	Continue()
END

>>>>>>>>
//EXTEND_BOTTOM ~%are2%.bcs~ ~.../%MOD_FOLDER%/inlined_BG0300.baf~ EVAL
*/
