<<<<<<<< .../%MOD_FOLDER%/inlined_BG0619.baf
////////////////////////////////////////////////////////////
// Door0805 trigger destination script
////////////////////////////////////////////////////////////
IF
    Global("BG0619_entered","%EBaldursGate%",1)
THEN
    RESPONSE #100
	TriggerActivation("Door0600",1)
	TriggerActivation("bggo_BG1100",0)
	SetGlobal("BG0619_entered","%EBaldursGate%",0)
END

IF
    Global("BG0619_entered","%SEBaldursGate%",1)
THEN
    RESPONSE #100
	TriggerActivation("Door0600",0)
	TriggerActivation("bggo_BG1100",1)
	SetGlobal("BG0619_entered","%SEBaldursGate%",0)
END
>>>>>>>> 

ACTION_IF FILE_EXISTS_IN_GAME ~%are2%.bcs~ BEGIN
	EXTEND_BOTTOM ~%are2%.bcs~ ~.../%MOD_FOLDER%/inlined_BG0619.baf~ EVAL
		
END ELSE BEGIN
	COPY ~.../%MOD_FOLDER%/inlined_BG0619.baf~ ~%workspace%/bif/temp/%are2%.baf~
	COMPILE EVAL ~%workspace%/bif/temp/%are2%.baf~
END
	