// BG0719 two entrances
<<<<<<<< .../%MOD_FOLDER%/inlined_BG0700_bottom.baf

// door a
IF
    Global("BGGO_opened_Door0719","%CentralBaldursGate%",0)
    Global("BGGO_opened_BG0719","GLOBAL",1)
THEN
	RESPONSE #100
		Unlock("Door0719")
		OpenDoor("Door0719")
		SetGlobal("BGGO_opened_Door0719","%CentralBaldursGate%",1)
		Continue()
END

IF
    OpenState("Door0719",TRUE)
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_Door0719","%CentralBaldursGate%",1)
		SetGlobal("BGGO_opened_BG0719","GLOBAL",1)
		Continue()
END

IF
    OpenState("Door0719",FALSE)
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_Door0719","%CentralBaldursGate%",0)
		SetGlobal("BGGO_opened_BG0719","GLOBAL",0)
		Continue()
END
// door b
IF
    Global("BGGO_opened_Door0719b","%CentralBaldursGate%",0)
    Global("BGGO_opened_BG0719b","GLOBAL",1)
THEN
	RESPONSE #100
		Unlock("Door0719b")
		OpenDoor("Door0719b")
		SetGlobal("BGGO_opened_Door0719b","%CentralBaldursGate%",1)
		Continue()
END

IF
    OpenState("Door0719b",TRUE)
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_Door0719b","%CentralBaldursGate%",1)
		SetGlobal("BGGO_opened_BG0719b","GLOBAL",1)
		Continue()
END

IF
    OpenState("Door0719b",FALSE)
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_Door0719b","%CentralBaldursGate%",0)
		SetGlobal("BGGO_opened_BG0719b","GLOBAL",0)
		Continue()
END
>>>>>>>>
EXTEND_TOP ~%are2%.bcs~ ~.../%MOD_FOLDER%/inlined_BG0700_bottom.baf~ EVAL

// BG0720 two entrances
<<<<<<<< .../%MOD_FOLDER%/inlined_BG0700_bottom.baf

// door a
IF
    Global("BGGO_opened_Door0720","%CentralBaldursGate%",0)
    Global("BGGO_opened_BG0720","GLOBAL",1)
THEN
	RESPONSE #100
		Unlock("Door0720")
		OpenDoor("Door0720")
		SetGlobal("BGGO_opened_Door0720","%CentralBaldursGate%",1)
		Continue()
END

IF
    OpenState("Door0720",TRUE)
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_Door0720","%CentralBaldursGate%",1)
		SetGlobal("BGGO_opened_BG0720","GLOBAL",1)
		Continue()
END

IF
    OpenState("Door0720",FALSE)
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_Door0720","%CentralBaldursGate%",0)
		SetGlobal("BGGO_opened_BG0720","GLOBAL",0)
		Continue()
END
// door b
IF
    Global("BGGO_opened_Door0720b","%CentralBaldursGate%",0)
    Global("BGGO_opened_BG0720b","GLOBAL",1)
THEN
	RESPONSE #100
		Unlock("Door0720b")
		OpenDoor("Door0720b")
		SetGlobal("BGGO_opened_Door0720b","%CentralBaldursGate%",1)
		Continue()
END

IF
    OpenState("Door0720b",TRUE)
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_Door0720b","%CentralBaldursGate%",1)
		SetGlobal("BGGO_opened_BG0720b","GLOBAL",1)
		Continue()
END

IF
    OpenState("Door0720b",FALSE)
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_Door0720b","%CentralBaldursGate%",0)
		SetGlobal("BGGO_opened_BG0720b","GLOBAL",0)
		Continue()
END
>>>>>>>>
EXTEND_TOP ~%are2%.bcs~ ~.../%MOD_FOLDER%/inlined_BG0700_bottom.baf~ EVAL
