<<<<<<<< .../%MOD_FOLDER%/open_door_triggerscript_a.baf
IF
	Clicked([ANYONE])
//	Global("BGGO_opened_BG0720","GLOBAL",0)
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_BG0720","GLOBAL",1)
END
>>>>>>>>

<<<<<<<< .../%MOD_FOLDER%/open_door_triggerscript_b.baf
IF
	Clicked([ANYONE])
//	Global("BGGO_opened_BG0720b","GLOBAL",0)
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_BG0720b","GLOBAL",1)
END
>>>>>>>>
COPY ~.../%MOD_FOLDER%/open_door_triggerscript_a.baf~ ~%workspace%/bif/temp/dr0720a.baf~ EVAL
COMPILE ~%workspace%/bif/temp/dr0720a.baf~ EVAL


COPY ~.../%MOD_FOLDER%/open_door_triggerscript_b.baf~ ~%workspace%/bif/temp/dr0720b.baf~ EVAL
COMPILE ~%workspace%/bif/temp/dr0720b.baf~ EVAL
