<<<<<<<< .../%MOD_FOLDER%/inlined_BG1200.baf
////////////////////////////////////////////////////////////
// Door01 east of BG1200 and west of BG1300
////////////////////////////////////////////////////////////
IF
	OpenState("bggo_Door01",TRUE)
THEN
	RESPONSE #100
	SetGlobal("%BaldursGateDocks%_door_open_door01","%BaldursGateDocks%",1)
	Continue()
END

IF
	OpenState("bggo_Door01",FALSE)
THEN
	RESPONSE #100
	SetGlobal("%BaldursGateDocks%_door_open_door01","%BaldursGateDocks%",0)
	Continue()
END


IF
	Global("%SEBaldursGate%_door_open_door01","%SEBaldursGate%",0)
THEN
	RESPONSE #100
	CloseDoor("bggo_Door01")
	Continue()
END
IF
	Global("%SEBaldursGate%_door_open_door01","%SEBaldursGate%",1)
THEN
	RESPONSE #100
	OpenDoor("bggo_Door01")
	Continue()
END

>>>>>>>> 

EXTEND_BOTTOM ~%are2%.bcs~ ~.../%MOD_FOLDER%/inlined_BG1200.baf~
	EVALUATE_BUFFER


