ACTION_IF MOD_IS_INSTALLED "setup-bst.tp2" (ID_OF_LABEL "setup-bst.tp2" "BS_BalduransSeatower-main" ) BEGIN

	////////////////////////////////////////////
	// BS0110.are
	////////////////////////////////////////////
	
	COPY_EXISTING ~bs0110.are~ ~override~
		////////////////////////////////////////////
		// trigger to leave to BG1300
		////////////////////////////////////////////
		LPF fj_are_structure
		INT_VAR
		fj_type         = 2    //travel
		fj_box_left     = 100
		fj_box_top      = 547
		fj_box_right    = 168
		fj_box_bottom   = 643
		fj_cursor_idx   = 42
		fj_vertex_0     = 102 + (547 << 16)
		fj_vertex_1     = 100 + (610 << 16)
		fj_vertex_2     = 168 + (643 << 16)
		fj_vertex_3     = 168 + (575 << 16)
		fj_flags        = BIT2 + BIT8  //full party required, autosave
		STR_VAR
		fj_structure_type   = region
		fj_name             = travar1300
		fj_destination_area = EVAL ~%SEBaldursGate%~
		fj_destination_name = bggo_Door01_exit
		END
	
	////////////////////////////////////////////
	// BS0110.BCS
	////////////////////////////////////////////	
	
		SPRINT area_name_house 	~BS0110~
		SPRINT area_name_1 		EVAL ~%BaldursGateDocks%~
		SPRINT area_name_2 		EVAL ~%SEBaldursGate%~
		
		GET_OFFSET_ARRAY triggers ARE_V10_REGIONS
		PHP_EACH triggers AS i => off BEGIN
			READ_ASCII off triggername (32) NULL
			READ_ASCII off + 0x38 destination
			PATCH_IF ~%destination%~ STR_EQ ~%area_name_1%~ BEGIN
				SPRINT trigger_name_1 ~%triggername%~
			END
			PATCH_IF ~%destination%~ STR_EQ ~%area_name_2%~ BEGIN
				SPRINT trigger_name_2 ~%triggername%~
			END
		END
		
	ACTION_IF FILE_EXISTS_IN_GAME ~%area_name_house%.bcs~ BEGIN
		EXTEND_BOTTOM ~%area_name_house%.bcs~ ~.../%MOD_FOLDER%/inlinedAreaScriptTriggerActivation.baf~ EVAL
	END ELSE BEGIN
		COPY ~.../%MOD_FOLDER%/inlinedAreaScriptTriggerActivation.baf~ ~%workspace%/bif/temp/%area_name_house%.baf~
		COMPILE EVAL ~%workspace%/bif/temp/%area_name_house%.baf~
	END
	
	////////////////////////////////////////////
	// BG1200.are BaldursGateDocks
	////////////////////////////////////////////
	
	COPY_EXISTING ~dest01xx.bcs~ ~override~
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY ~BG01xx~ ~BS0110~
		END
	
	COPY_EXISTING ~%BaldursGateDocks%.are~ ~override~
		GET_OFFSET_ARRAY entrances ARE_V10_ENTRANCES 
		PHP_EACH entrances AS i => off BEGIN
			READ_ASCII off entrancename (32) NULL
			PATCH_IF ~%entrancename%~ STR_EQ ~exit_bg01xx~ BEGIN
				LPF fj_are_structure
					INT_VAR fj_delete_mode = i
					STR_VAR fj_structure_type = entrance
				END
			END
		END
	
	////////////////////////////////////////////
	// BG1300.are SEBaldursGate
	////////////////////////////////////////////
	
	COPY_EXISTING ~dest01xx.bcs~ ~override~
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY ~BG01xx~ ~BS0110~
		END
	
	COPY_EXISTING ~%SEBaldursGate%.are~ ~override~
		GET_OFFSET_ARRAY doors ARE_V10_DOORS
		PHP_EACH doors AS i => off BEGIN
			READ_ASCII off + 0x20 door_id
			PATCH_IF ~%door_id%~ STR_EQ ~door1300~ BEGIN
				WRITE_LONG off + 0x28 BIT6	// is door
				WRITE_LONG off + 0x88 0		// detection difficulty
			END
		END
		
		GET_OFFSET_ARRAY triggers ARE_V10_REGIONS
		PHP_EACH triggers AS i => off BEGIN
			READ_ASCII off triggername (32) NULL
			PATCH_IF ~%triggername%~ STR_EQ ~bggo_Door01~ BEGIN
				WRITE_ASCII off + 0x38 ~BS0110~		// destination
				WRITE_ASCII off + 0x40 ~exitar1200~ #32	// exit
				WRITE_LONG  off + 0x60 BIT10 + BIT11 // BIT10 activation point BIT11 connected to door
			END
			PATCH_IF ~%triggername%~ STR_EQ ~bggo_InfoHouse~ BEGIN
				WRITE_LONG off + 0x60 (THIS | BIT8) //deactivates
			END
		END
END
