<<<<<<<< .../%MOD_FOLDER%/inlined_door_flame.baf
IF
  OpenState("%door_name%",TRUE)
THEN
  RESPONSE #100
    AmbientActivate("%animation_name%",FALSE)
    Continue()
END

IF
  OpenState("%door_name%",FALSE)
THEN
  RESPONSE #100
	AmbientActivate("%animation_name%",TRUE)
	Continue()
END
>>>>>>>> 


<<<<<<<< .../%MOD_FOLDER%/inlined_bggodest.baf
IF
    True()
THEN
    RESPONSE #100
	SetGlobal("%area_name%_entered","MYAREA",1)
END
>>>>>>>>


<<<<<<<< .../%MOD_FOLDER%/inlined_door_open_close.baf

%global_unlock_door%

IF
	Global("BGGO_opened_%door_name%","GLOBAL",0)
THEN
	RESPONSE #100
	CloseDoor("%door_name%")
	Continue()
END
IF
	Global("BGGO_opened_%door_name%","GLOBAL",1)
THEN
	RESPONSE #100
	OpenDoor("%door_name%")
	Continue()
END

>>>>>>>> 


<<<<<<<< .../%MOD_FOLDER%/inlined_door_script.baf

%set_unlock_door%

IF
	Clicked([ANYONE])
    OpenState("%door_name%",TRUE)
	Global("BGGO_unlocked_%door_name%","GLOBAL",1)
//    Opened([ANYONE])
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_%door_name%","GLOBAL",1)
END

IF
	Clicked([ANYONE])
    OpenState("%door_name%",FALSE)
	Global("BGGO_unlocked_%door_name%","GLOBAL",1)
//	Closed([ANYONE])
THEN
    RESPONSE #100
		SetGlobal("BGGO_opened_%door_name%","GLOBAL",0)
END

%door_click%

>>>>>>>>


<<<<<<<< .../%MOD_FOLDER%/inlinedAreaScriptTriggerActivation.baf
////////////////////////////////////////////////////////////
// Door0805 trigger destination script
////////////////////////////////////////////////////////////
IF
    Global("%are%_entered","%area_name_1%",1)
THEN
    RESPONSE #100
	TriggerActivation("%trigger_name_1%",1)
	TriggerActivation("%trigger_name_2%",0)
	SetGlobal("%are%_entered","%area_name_2%",0)
END

IF
    Global("%are%_entered","%area_name_2%",1)
THEN
    RESPONSE #100
	TriggerActivation("%trigger_name_1%",0)
	TriggerActivation("%trigger_name_2%",1)
	SetGlobal("%are%_entered","%area_name_1%",0)
END
>>>>>>>> 