
//Add candles and torches
PATCH_DEFINE_ARRAY x_coord BEGIN 619 512 454 671 288 180 END
PATCH_DEFINE_ARRAY y_coord BEGIN 317 147 291 398 471 482 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule =  0b111111111111111111111111 //Hours 0.00 - 24.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLMS
		fj_bam_resref = FLMS //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 175 355 362 440 445 450 445 297 306 828 END
PATCH_DEFINE_ARRAY y_coord BEGIN 628 548 541 498 494 497 501 705 709 284 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111111111111111111111111 //Hours 0.00 - 24.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLAME2N
		fj_bam_resref = FLAME2N
	END
END
LPM ~CLEAR_ARRAY~

////////////////////////////////////////////
// trigger to leave to BG0200 **
////////////////////////////////////////////
SNPRINT "-4" exitvar ~%CentralBaldursGate_OberonsEstate_L1%~ //BG0143
LPF fj_are_structure
    INT_VAR
    fj_type         = 2    //travel
    fj_box_left     = 641
    fj_box_top      = 424
    fj_box_right    = 745
    fj_box_bottom   = 564
	fj_flags        = BIT8 //BIT8 deativated
    fj_cursor_idx   = 30   //door
	fj_vertex_0  = 641 + (485 << 16)
	fj_vertex_1  = 694 + (564 << 16)
	fj_vertex_2  = 745 + (475 << 16)
	fj_vertex_3  = 700 + (424 << 16)
    STR_VAR
    fj_structure_type   = region
    fj_name             = bggo_BG0200
    fj_destination_area = EVAL ~%NBaldursGate%~
    fj_destination_name = EVAL ~Exit%exitvar%~ //Exit0143
END

LPF CreateHouseAreaScript
	STR_VAR
		area_name_house 	= EVAL ~%CentralBaldursGate_OberonsEstate_L1%~
		area_name_1 		= EVAL ~%NBaldursGate%~
		area_name_2 		= EVAL ~%CentralBaldursGate%~
END
