//**************************************************
// Add some braziers in Baldur's Gate
//**************************************************

PATCH_DEFINE_ARRAY x_coord BEGIN 2853 2246 133  310  386  2165 END
PATCH_DEFINE_ARRAY y_coord BEGIN 499  555  1645 2295 3155 1279 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = Brazier
		fj_bam_resref = fire_3
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 1137 1215 1324 END
PATCH_DEFINE_ARRAY y_coord BEGIN 1617 1580 2601 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule =  0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLMS
		fj_bam_resref = FLMS //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 1740 1893 4234 3909 4168 END
PATCH_DEFINE_ARRAY y_coord BEGIN 2072 1945 1429 572  529  END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")+2
		fj_loc_y = $y_coord("%index%")-12
		fj_schedule =  0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FIRE_4
		fj_bam_resref = FIRE_4 //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 1736 1786 3690 2980 3026 2390 2505 2568 2691 2783 2357 2345 END
PATCH_DEFINE_ARRAY y_coord BEGIN 2466 2449 2205 1599 1669 986  927  916  896  879  1306 1351 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLAME2N
		fj_bam_resref = FLAME2N //bgrd
	END
END
LPM ~CLEAR_ARRAY~

////////////////////////////////////////////////////////////
//  Door0157  The flame to the left of the door is hidden by the open door.
////////////////////////////////////////////////////////////

PATCH_DEFINE_ARRAY x_coord BEGIN 3641 END
PATCH_DEFINE_ARRAY y_coord BEGIN 2170 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		fj_transparent = 0
		STR_VAR
		fj_structure_type = animation
		fj_name = FlmDoor0157
		fj_bam_resref = FLAME2N //bgrd
	END
END
LPM ~CLEAR_ARRAY~

// Create the doorscript for animations
LPF CreateDoorScriptPatchAnimation
STR_VAR
	animation_name   = FlmDoor0157
	door_name   	 = Door0157
END

// Rename the triggers to avoid confusion add door script
LPF Door_trigger_script_patch
STR_VAR
	door_name		 = Door0157
	new_trigger_name = bggo_BG0157
	door_script		 = Door0157
END

//////////////////////////////
// Door0159 from BG0200
//////////////////////////////
LPF CreateTriggerScriptBggodest
STR_VAR
	script_name = dest0159
	area_name = EVAL ~%NWBaldursGate_House1_L1%~
RET
	script_name
END

LPF Door_trigger_script_patch
STR_VAR
	door_name	 		= Door0159
	new_trigger_name	= bggo_BG0159
	trigger_script   	= EVAL ~%script_name%~
END

LPF CreateAreaTravelScript
	INT_VAR
		bggo_locked	   = 1
	STR_VAR
		from_area 	   = EVAL ~%NWBaldursGate%~
		to_area   	   = EVAL ~%NBaldursGate%~
		door_name_from = Door0159
END