//////////////////////////////////////
// identical maps: BG0169
// BG0012 BG0014 BG0159 BG0169 BG0709 BG0715 BG0801 BG0813 BG1203 BG1213 BG1308 BG1316 BG3313 BG3325 BG3331 BG3345 BG3349
//////////////////////////////////////

SPRINT identical_area "BG0169"

PATCH_IF FILE_EXISTS ~%MOD_FOLDER%/base/are_patch/%identical_area%_are.tpa~ BEGIN // add animation for braziers, candles ...
	PATCH_INCLUDE ~%MOD_FOLDER%/base/are_patch/%identical_area%_are.tpa~
END

////////////////////////////////////////////
// trigger to leave to BG0200 *
////////////////////////////////////////////
SNPRINT "-4" exitvar ~%NWBaldursGate_House1_L1%~ //BG0159
LPF fj_are_structure
    INT_VAR
    fj_type         = 2    //travel
    fj_box_left     = 419
    fj_box_top      = 302
    fj_box_right    = 500
    fj_box_bottom   = 420
	fj_flags        = BIT8 //BIT8 deativated
    fj_cursor_idx   = 30   //door
	fj_vertex_0  = 419 + (341 << 16)
	fj_vertex_1  = 419 + (341 << 16)
	fj_vertex_2  = 419 + (420 << 16)
	fj_vertex_3  = 500 + (380 << 16)
	fj_vertex_4  = 500 + (302 << 16)
    STR_VAR
    fj_structure_type   = region
    fj_name             = bggo_BG0200
    fj_destination_area = EVAL ~%NBaldursGate%~
    fj_destination_name = EVAL ~Exit%exitvar%~ //Exit0159
END

LPF CreateHouseAreaScript
	STR_VAR
		area_name_house 	= EVAL ~%NWBaldursGate_House1_L1%~
		area_name_1 		= EVAL ~%NWBaldursGate%~
		area_name_2 		= EVAL ~%NBaldursGate%~
END
