//**************************************************
// Add some braziers in Baldur's Gate
//**************************************************

PATCH_DEFINE_ARRAY x_coord BEGIN 941 3314 603 609 1936 1437 END
PATCH_DEFINE_ARRAY y_coord BEGIN 80  207  580 853 2517 2027 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = Brazier
		fj_bam_resref = fire_3
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 2056 2251 END
PATCH_DEFINE_ARRAY y_coord BEGIN 1510 1699 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
		INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = Brazier
		fj_bam_resref = flame2l
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 9   74   343  2074 2194  END
PATCH_DEFINE_ARRAY y_coord BEGIN 529 1431 1378 1946 1977  END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")+2
		fj_loc_y = $y_coord("%index%")-12
		fj_schedule =  0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001000011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FIRE_4
		fj_bam_resref = FIRE_4 //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 1242 END
PATCH_DEFINE_ARRAY y_coord BEGIN 2794 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLMS
		fj_bam_resref = FLMS //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 214  726  784  1570 4308 4025 3043 2743 2668 2476  END
PATCH_DEFINE_ARRAY y_coord BEGIN 2238 2652 2667 2879 772  880  1158 1062 1056 1204  END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLAME2N
		fj_bam_resref = FLAME2N //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 2388 END
PATCH_DEFINE_ARRAY y_coord BEGIN 3149 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111111111111111111111111 //Hours 0.00 - 24.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = flamlav1
		fj_bam_resref = flamlav1
	END
END
LPM ~CLEAR_ARRAY~

//////////////////////////////
// Door0159 from BG0100
//////////////////////////////
LPF CreateTriggerScriptBggodest
STR_VAR
	script_name = dest0159
	area_name = BG0159
RET
	script_name
END

LPF Door_trigger_script_patch
STR_VAR
	door_name_wed	 	= DOOR03
	new_trigger_name	= bggo_BG0159
	trigger_script   	= EVAL ~%script_name%~
RET
	travel_trigger_found
	bggo_deleted
	existing_door_name
END

LPF CreateAreaTravelScript
	INT_VAR
		bggo_locked	   = 1
	STR_VAR
		from_area 	   = EVAL ~%NBaldursGate%~
		to_area   	   = EVAL ~%NWBaldursGate%~
		door_name 	   = DOOR0159
		old_door_name  = EVAL ~%existing_door_name%~
END

PATCH_IF bggo_deleted = 1 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_flags               = 0b01000010 //0b010000000
		fj_open_box_left       = 7
		fj_open_box_top        = 2347
		fj_open_box_right      = 29
		fj_open_box_bottom     = 2429
		fj_closed_box_left     = 5
		fj_closed_box_top      = 2325
		fj_closed_box_right    = 41
		fj_closed_box_bottom   = 2407
		fj_cursor_idx          = 30
		fj_trap_loc_x		   = 54
		fj_trap_loc_y		   = 2324
		fj_open_loc_x          = 53
		fj_open_loc_y          = 2419
		fj_closed_loc_x        = 53
		fj_closed_loc_y        = 2419
		fj_locked_diff		   = 30
		fj_door_open_vert_0    = 7  + (2404 << 16)
		fj_door_open_vert_1    = 29 + (2429 << 16)
		fj_door_open_vert_2    = 29 + (2376 << 16)
		fj_door_open_vert_3    = 26 + (2365 << 16)
		fj_door_open_vert_4    = 23 + (2359 << 16)
		fj_door_open_vert_5    = 21 + (2354 << 16)
		fj_door_open_vert_6    = 17 + (2349 << 16)
		fj_door_open_vert_7    = 15 + (2347 << 16)
		fj_door_open_vert_8    = 12 + (2348 << 16)
		fj_door_open_vert_9    = 9  + (2348 << 16)
		fj_door_open_vert_10   = 7  + (2350 << 16)
		                               
		fj_door_closed_vert_0  = 5  + (2407 << 16)
		fj_door_closed_vert_1  = 41 + (2382 << 16)
		fj_door_closed_vert_2  = 41 + (2328 << 16)
		fj_door_closed_vert_3  = 36 + (2325 << 16)
		fj_door_closed_vert_4  = 28 + (2327 << 16)
		fj_door_closed_vert_5  = 23 + (2330 << 16)
		fj_door_closed_vert_6  = 18 + (2333 << 16)
		fj_door_closed_vert_7  = 12 + (2339 << 16)
		fj_door_closed_vert_8  = 8  + (2345 << 16)
		fj_door_closed_vert_9  = 5  + (2353 << 16)

		fj_cell_open_vert_0    = 1 + (202 << 16)
		fj_cell_open_vert_1    = 1 + (201 << 16)

		fj_cell_closed_vert_0  = 1 + (199 << 16)
		fj_cell_closed_vert_1  = 1 + (198 << 16)
		fj_cell_closed_vert_2  = 1 + (197 << 16)
		fj_cell_closed_vert_3  = 1 + (196 << 16)

		STR_VAR
		fj_travel_trigger      = bggo_BG0159
		fj_structure_type      = door
		fj_name                = Door0159
		fj_door_wed_id         = Door03
	END
END

PATCH_IF travel_trigger_found = 0 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_type         = 2    //travel
		fj_box_left     = 9
		fj_box_top      = 2329
		fj_box_right    = 38
		fj_box_bottom   = 2399
		fj_cursor_idx   = 30   //door
		fj_flags        = 0b000100000000000
		fj_vertex_0  = 9  + (2399 << 16)
		fj_vertex_1  = 38 + (2377 << 16)
		fj_vertex_2  = 38 + (2330 << 16)
		fj_vertex_3  = 33 + (2329 << 16)
		fj_vertex_4  = 25 + (2332 << 16)
		fj_vertex_5  = 20 + (2336 << 16)
		fj_vertex_6  = 16 + (2341 << 16)
		fj_vertex_7  = 12 + (2348 << 16)
		fj_vertex_8  = 9  + (2355 << 16)
		STR_VAR
		fj_structure_type   = region
		fj_name             = bggo_BG0159
		fj_destination_area = BG0159
		fj_destination_name = Exit0100
		fj_reg_script       = dest0159
	END
	
	LPF fj_are_structure
		INT_VAR
		fj_loc_x       = 28
		fj_loc_y       = 2440
		fj_orientation = 13
		STR_VAR
		fj_structure_type = entrance
		fj_name           = Exit0159
	END
END
