//**************************************************
// Add some braziers in Baldur's Gate
//**************************************************

PATCH_DEFINE_ARRAY x_coord BEGIN 941 3314 603 609 1936 1437 END
PATCH_DEFINE_ARRAY y_coord BEGIN 80  207  580 853 2517 2027 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = Brazier
		fj_bam_resref = fire_3
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 2056 2251 END
PATCH_DEFINE_ARRAY y_coord BEGIN 1510 1699 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
		INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = Brazier
		fj_bam_resref = flame2l
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 9   74   343  2074 2194  END
PATCH_DEFINE_ARRAY y_coord BEGIN 529 1431 1378 1946 1977  END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")+2
		fj_loc_y = $y_coord("%index%")-12
		fj_schedule =  0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001000011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FIRE_4
		fj_bam_resref = FIRE_4 //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 1242 END
PATCH_DEFINE_ARRAY y_coord BEGIN 2794 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLMS
		fj_bam_resref = FLMS //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 214  726  784  1570 4308 4025 3043 2743 2668 2476  END
PATCH_DEFINE_ARRAY y_coord BEGIN 2238 2652 2667 2879 772  880  1158 1062 1056 1204  END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLAME2N
		fj_bam_resref = FLAME2N //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 2388 END
PATCH_DEFINE_ARRAY y_coord BEGIN 3149 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111111111111111111111111 //Hours 0.00 - 24.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = flamlav1
		fj_bam_resref = flamlav1
	END
END
LPM ~CLEAR_ARRAY~



//////////////////////////////
// Door0159 from BG0100 **
//////////////////////////////
SNPRINT "-4" CmpAreaNumDest ~%NWBaldursGate_House1_L1%~ //BG0159
SNPRINT "-4" CmpAreaNum ~%NWBaldursGate%~ // for exit name
LPF CreateTriggerScriptBggodest
STR_VAR
	trigger_script = EVAL ~dest%CmpAreaNumDest%~ //bggo_BG0159
	area_name_dest = EVAL ~%NWBaldursGate_House1_L1%~ //BG0159
RET
	trigger_script
	area_name_dest
END

LPF Door_trigger_script_patch
STR_VAR
	door_name_wed	 	= DOOR03
	door_name			= Door0159
	area_name			= EVAL ~%NBaldursGate%~
	new_trigger_name	= EVAL ~bggo_Door%CmpAreaNumDest%~ //bggo_BG0159
	trigger_script   	= EVAL ~%trigger_script%~
	door_script			= EVAL ~dr%CmpAreaNumDest%02~ //dr015902
	area_name_dest		= EVAL ~%area_name_dest%~
RET
	travel_trigger_found
	bggo_deleted
	existing_door_name
	door_script
END

PATCH_IF bggo_deleted = 1 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_flags               = BIT6 //BIT1 locked BIT6 is door
		fj_open_box_left       = 7
		fj_open_box_top        = 2347
		fj_open_box_right      = 29
		fj_open_box_bottom     = 2429
		fj_closed_box_left     = 5
		fj_closed_box_top      = 2325
		fj_closed_box_right    = 41
		fj_closed_box_bottom   = 2407
		fj_cursor_idx          = 30
		fj_trap_loc_x		   = 54
		fj_trap_loc_y		   = 2324
		fj_open_loc_x          = 53
		fj_open_loc_y          = 2419
		fj_closed_loc_x        = 53
		fj_closed_loc_y        = 2419
		fj_locked_diff		   = 30
		fj_door_open_vert_0    = 7  + (2404 << 16)
		fj_door_open_vert_1    = 29 + (2429 << 16)
		fj_door_open_vert_2    = 29 + (2376 << 16)
		fj_door_open_vert_3    = 26 + (2365 << 16)
		fj_door_open_vert_4    = 23 + (2359 << 16)
		fj_door_open_vert_5    = 21 + (2354 << 16)
		fj_door_open_vert_6    = 17 + (2349 << 16)
		fj_door_open_vert_7    = 15 + (2347 << 16)
		fj_door_open_vert_8    = 12 + (2348 << 16)
		fj_door_open_vert_9    = 9  + (2348 << 16)
		fj_door_open_vert_10   = 7  + (2350 << 16)
		                               
		fj_door_closed_vert_0  = 5  + (2407 << 16)
		fj_door_closed_vert_1  = 41 + (2382 << 16)
		fj_door_closed_vert_2  = 41 + (2328 << 16)
		fj_door_closed_vert_3  = 36 + (2325 << 16)
		fj_door_closed_vert_4  = 28 + (2327 << 16)
		fj_door_closed_vert_5  = 23 + (2330 << 16)
		fj_door_closed_vert_6  = 18 + (2333 << 16)
		fj_door_closed_vert_7  = 12 + (2339 << 16)
		fj_door_closed_vert_8  = 8  + (2345 << 16)
		fj_door_closed_vert_9  = 5  + (2353 << 16)

		fj_cell_open_vert_0    = 1 + (202 << 16)
		fj_cell_open_vert_1    = 1 + (201 << 16)

		fj_cell_closed_vert_0  = 1 + (199 << 16)
		fj_cell_closed_vert_1  = 1 + (198 << 16)
		fj_cell_closed_vert_2  = 1 + (197 << 16)
		fj_cell_closed_vert_3  = 1 + (196 << 16)

		STR_VAR
		fj_travel_trigger      = EVAL ~bggo_Door%CmpAreaNumDest%~ //bggo_BG0159
		fj_structure_type      = door
		fj_name                = EVAL ~%existing_door_name%~
		fj_door_wed_id         = Door03
		fj_door_script		   = EVAL ~%door_script%~
	END
END

PATCH_IF travel_trigger_found = 0 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_type         = 2    //travel
		fj_box_left     = 9
		fj_box_top      = 2329
		fj_box_right    = 38
		fj_box_bottom   = 2399
		fj_cursor_idx   = 30   //door
		fj_flags        = BIT11  //BIT11 door connected
		fj_vertex_0  = 9  + (2399 << 16)
		fj_vertex_1  = 38 + (2377 << 16)
		fj_vertex_2  = 38 + (2330 << 16)
		fj_vertex_3  = 33 + (2329 << 16)
		fj_vertex_4  = 25 + (2332 << 16)
		fj_vertex_5  = 20 + (2336 << 16)
		fj_vertex_6  = 16 + (2341 << 16)
		fj_vertex_7  = 12 + (2348 << 16)
		fj_vertex_8  = 9  + (2355 << 16)
		STR_VAR
		fj_structure_type   = region
		fj_name             = EVAL ~bggo_Door%CmpAreaNumDest%~ //bggo_BG0159
		fj_destination_area = EVAL ~%NWBaldursGate_House1_L1%~
		fj_destination_name = EVAL ~Exit%CmpAreaNum%~ //Exit0100
		fj_reg_script       = EVAL ~%trigger_script%~
	END
	
	LPF fj_are_structure
		INT_VAR
		fj_loc_x       = 28
		fj_loc_y       = 2440
		fj_orientation = 13
		STR_VAR
		fj_structure_type = entrance
		fj_name           = EVAL ~Exit%CmpAreaNumDest%~ //Exit0159
	END
END

/////////////////////////////////////////////////////////
// Door0143 to BG0700 **
/////////////////////////////////////////////////////////
SNPRINT "-4" CmpAreaNumDest ~%CentralBaldursGate_OberonsEstate_L1%~ //BG0143
SNPRINT "-4" CmpAreaNum ~%CentralBaldursGate%~ //BG0700
LPF CreateTriggerScriptBggodest
STR_VAR
	trigger_script = EVAL ~dest%CmpAreaNumDest%~ //dest0143
	area_name_dest = EVAL ~%CentralBaldursGate_OberonsEstate_L1%~ //BG0143
RET
	trigger_script
	area_name_dest
END

LPF Door_trigger_script_patch
INT_VAR
	bggo_locked 		  = 1	// is door locked =1 unlocked =0
STR_VAR
	door_name_wed	 	= DOOR0143
	door_name			= Door0143
	area_name			= EVAL ~%NBaldursGate%~
	new_trigger_name	= EVAL ~bggo_Door%CmpAreaNumDest%~ //bggo_BG0143
	trigger_script   	= EVAL ~%trigger_script%~
	door_script			= EVAL ~dr%CmpAreaNumDest%2~ //dr01432
	area_name_dest		= EVAL ~%area_name_dest%~
RET
	travel_trigger_found
	bggo_deleted
	existing_door_name
	door_script
END

PATCH_IF bggo_deleted = 1 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_flags               = BIT1 + BIT6 //BIT1 locked BIT6 is door
		fj_open_box_left       = 3430
		fj_open_box_top        = 3127
		fj_open_box_right      = 3482
		fj_open_box_bottom     = 3192
		fj_closed_box_left     = 3394
		fj_closed_box_top      = 3112
		fj_closed_box_right    = 3429
		fj_closed_box_bottom   = 3198
		fj_cursor_idx          = 30
		fj_open_loc_x          = 3500
		fj_open_loc_y          = 3170
		fj_closed_loc_x        = 3500
		fj_closed_loc_y        = 3170
		fj_locked_diff		   = 30
		fj_door_open_vert_0    = 3430 + (3182 << 16)
		fj_door_open_vert_1    = 3482 + (3192 << 16)
		fj_door_open_vert_2    = 3482 + (3137 << 16)
		fj_door_open_vert_3    = 3430 + (3127 << 16)
		fj_door_closed_vert_0  = 3429 + (3176 << 16)
		fj_door_closed_vert_1  = 3413 + (3198 << 16)
		fj_door_closed_vert_2  = 3394 + (3198 << 16)
		fj_door_closed_vert_3  = 3398 + (3177 << 16)
		fj_door_closed_vert_4  = 3404 + (3155 << 16)
		fj_door_closed_vert_5  = 3414 + (3132 << 16)
		fj_door_closed_vert_6  = 3422 + (3119 << 16)
		fj_door_closed_vert_7  = 3429 + (3112 << 16)

		fj_cell_closed_vert_0    = 213 + (266 << 16)
		fj_cell_closed_vert_1    = 214 + (264 << 16)
		fj_cell_closed_vert_2    = 214 + (265 << 16)
		fj_cell_closed_vert_3    = 213 + (265 << 16)
		fj_cell_open_vert_0      = 214 + (264 << 16)
		fj_cell_open_vert_1      = 215 + (264 << 16)
		fj_cell_open_vert_2      = 216 + (264 << 16)
		fj_cell_open_vert_3      = 217 + (264 << 16)
		fj_cell_open_vert_4      = 214 + (263 << 16)
		fj_cell_open_vert_5      = 215 + (263 << 16)
		fj_cell_open_vert_6      = 214 + (262 << 16)
		fj_cell_open_vert_7      = 215 + (262 << 16)
//		fj_cell_open_vert_8      = 214 + (265 << 16)
//		fj_cell_open_vert_9      = 215 + (265 << 16)
//		fj_cell_open_vert_10     = 216 + (265 << 16)
//		fj_cell_open_vert_11     = 217 + (265 << 16)
		STR_VAR
		fj_travel_trigger      = EVAL ~bggo_Door%CmpAreaNumDest%~ //bggo_BG0143
		fj_structure_type      = door
		fj_name                = EVAL ~%existing_door_name%~
		fj_door_wed_id         = DOOR0143
		fj_door_script		   = EVAL ~%door_script%~
	END
END

PATCH_IF travel_trigger_found = 0 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_type         = 2    //travel
		fj_box_left     = 3394
		fj_box_top      = 3112
		fj_box_right    = 3429
		fj_box_bottom   = 3198
		fj_cursor_idx   = 30   //door
		fj_flags        = BIT11  //BIT11 door connected
		fj_vertex_0  = 3429 + (3176 << 16)
		fj_vertex_1  = 3413 + (3198 << 16)
		fj_vertex_2  = 3394 + (3198 << 16)
		fj_vertex_3  = 3398 + (3177 << 16)
		fj_vertex_4  = 3404 + (3155 << 16)
		fj_vertex_5  = 3414 + (3132 << 16)
		fj_vertex_6  = 3422 + (3119 << 16)
		fj_vertex_7  = 3429 + (3112 << 16)
		STR_VAR
		fj_structure_type   = region
		fj_name             = EVAL ~bggo_Door%CmpAreaNumDest%~ //bggo_BG0143
		fj_destination_area = EVAL ~%CentralBaldursGate_OberonsEstate_L1%~
		fj_destination_name = EVAL ~Exit%CmpAreaNum%~ //Exit0700
		fj_reg_script       = EVAL ~%trigger_script%~
	END
	
	LPF fj_are_structure
		INT_VAR
		fj_loc_x       = 3510
		fj_loc_y       = 3170
		fj_orientation = 12
		STR_VAR
		fj_structure_type = entrance
		fj_name           = EVAL ~Exit%CmpAreaNumDest%~ //Exit0143
	END
END

//////////////////////////////
// Door0114 from BG0300 **
//////////////////////////////

SNPRINT "-4" CmpAreaNumDest ~%NEBaldursGate_BlushingMermaid_L1%~ //BG0114
LPF CreateTriggerScriptBggodest
STR_VAR
	trigger_script = EVAL ~dest%CmpAreaNumDest%~ //dest0114
	area_name_dest = EVAL ~%NEBaldursGate_BlushingMermaid_L1%~ //BG0114
RET
	trigger_script
	area_name_dest
END

LPF Door_trigger_script_patch
INT_VAR
	bggo_locked 		  = 1	// is door locked =1 unlocked =0
STR_VAR
	door_name_wed	 	= DOOR05
	door_name			= Dr0114b
	area_name			= EVAL ~%NBaldursGate%~
	new_trigger_name	= EVAL ~bggo_Door%CmpAreaNumDest%b~ //bggo_BG0114b
	trigger_script   	= EVAL ~%trigger_script%~
	door_script			= EVAL ~dr%CmpAreaNumDest%b2~ //dr0114b2
	area_name_dest		= EVAL ~%area_name_dest%~
	trigger_name_dialog = "Trigger Point 31"
RET
	travel_trigger_found
	bggo_deleted
	existing_door_name
	door_script
	dialog_string
END
SET DialogStringBG0200 = dialog_string

PATCH_IF bggo_deleted = 1 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_flags               = BIT1 + BIT6 //BIT1 locked BIT6 is door
		fj_open_box_left       = 4334
		fj_open_box_top        = 1376
		fj_open_box_right      = 4367
		fj_open_box_bottom     = 1453
		fj_closed_box_left     = 4358
		fj_closed_box_top      = 1376
		fj_closed_box_right    = 4388
		fj_closed_box_bottom   = 1444
		fj_cursor_idx          = 30
		fj_trap_loc_x		   = 4363
		fj_trap_loc_y		   = 1483
		fj_open_loc_x          = 4365
		fj_open_loc_y          = 1481
		fj_closed_loc_x        = 4365
		fj_closed_loc_y        = 1481
		fj_locked_diff		   = 30
		fj_door_open_vert_0    = 4367 + (1426 << 16)
		fj_door_open_vert_1    = 4337 + (1453 << 16)
		fj_door_open_vert_2    = 4334 + (1451 << 16)
		fj_door_open_vert_3    = 4335 + (1401 << 16)
		fj_door_open_vert_4    = 4340 + (1390 << 16)
		fj_door_open_vert_5    = 4347 + (1381 << 16)
		fj_door_open_vert_6    = 4354 + (1376 << 16)
		fj_door_open_vert_7    = 4367 + (1377 << 16)
		                                 
		fj_door_closed_vert_0  = 4358 + (1422 << 16)
		fj_door_closed_vert_1  = 4388 + (1444 << 16)
		fj_door_closed_vert_2  = 4388 + (1398 << 16)
		fj_door_closed_vert_3  = 4383 + (1390 << 16)
		fj_door_closed_vert_4  = 4374 + (1379 << 16)
		fj_door_closed_vert_5  = 4367 + (1376 << 16)
		fj_door_closed_vert_6  = 4358 + (1377 << 16)

		fj_cell_open_vert_0    = 271 + (118 << 16)
		fj_cell_open_vert_1    = 271 + (119 << 16)
		fj_cell_open_vert_2    = 271 + (118 << 16)

		fj_cell_closed_vert_0  = 272 + (116 << 16)
		fj_cell_closed_vert_1  = 272 + (117 << 16)
		fj_cell_closed_vert_2  = 273 + (117 << 16)
		fj_cell_closed_vert_3  = 273 + (118 << 16)
		fj_cell_closed_vert_4  = 274 + (118 << 16)
		fj_cell_closed_vert_5  = 274 + (119 << 16)
		fj_cell_closed_vert_6  = 275 + (119 << 16)
		fj_cell_closed_vert_7  = 275 + (120 << 16)
		
		STR_VAR
		fj_travel_trigger      = EVAL ~bggo_Door%CmpAreaNumDest%b~ //bggo_BG0114b
		fj_structure_type      = door
		fj_name                = EVAL ~%existing_door_name%~
		fj_door_wed_id         = DOOR05
		fj_door_script		   = EVAL ~%door_script%~
	END
END

PATCH_IF travel_trigger_found = 0 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_type         = 2    //travel
		fj_box_left     = 4358
		fj_box_top      = 1376
		fj_box_right    = 4388
		fj_box_bottom   = 1444
		fj_cursor_idx   = 30
		fj_alt_x		= 4368
		fj_alt_y		= 1447
		fj_flags        = BIT10 + BIT11  //BIT10 activation point BIT11 door connected
		fj_vertex_0  = 4358 + (1422 << 16)
		fj_vertex_1  = 4388 + (1444 << 16)
		fj_vertex_2  = 4388 + (1398 << 16)
		fj_vertex_3  = 4383 + (1390 << 16)
		fj_vertex_4  = 4374 + (1379 << 16)
		fj_vertex_5  = 4367 + (1376 << 16)
		fj_vertex_6  = 4358 + (1377 << 16)
		STR_VAR
		fj_structure_type   = region
		fj_name             = EVAL ~bggo_Door%CmpAreaNumDest%b~ //bggo_BG0114b
		fj_destination_area = EVAL ~%NEBaldursGate_BlushingMermaid_L1%~
		fj_destination_name = bggo_Exit0300 // new exit
		fj_reg_script       = EVAL ~%trigger_script%~ //dest0114
	END

	LPF fj_are_structure
		INT_VAR
		fj_loc_x       = 4340
		fj_loc_y       = 1467
		fj_orientation = 2
		STR_VAR
		fj_structure_type = entrance
		fj_name           = bggo_Exit0114b // new exit
	END
END

/////////////////////////////////////////////////////////
// Door Object 12 is connected to Door0014
/////////////////////////////////////////////////////////

LPF Door_trigger_script_patch 
STR_VAR
	door_name_wed	 	= DOOR02
	door_name			= ~Door0014~
RET
	travel_trigger_found
	bggo_deleted
	existing_door_name
	door_script
END

PATCH_IF bggo_deleted = 1 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_flags               = BIT6 //BIT6 is door
		fj_open_box_left       = 3030
		fj_open_box_top        = 1160
		fj_open_box_right      = 3063
		fj_open_box_bottom     = 1205
		fj_closed_box_left     = 3025
		fj_closed_box_top      = 1160
		fj_closed_box_right    = 3030
		fj_closed_box_bottom   = 1230
		fj_cursor_idx          = 30
		fj_open_loc_x          = 3074
		fj_open_loc_y          = 1198
		fj_closed_loc_x        = 3074
		fj_closed_loc_y        = 1198
		fj_door_open_vert_0    = 3030 + (1199 << 16)
		fj_door_open_vert_1    = 3063 + (1205 << 16)
		fj_door_open_vert_2    = 3063 + (1165 << 16)
		fj_door_open_vert_3    = 3030 + (1160 << 16)
		fj_door_closed_vert_0  = 3025 + (1230 << 16)
		fj_door_closed_vert_1  = 3030 + (1199 << 16)
		fj_door_closed_vert_2  = 3030 + (1160 << 16)
		fj_door_closed_vert_3  = 3025 + (1191 << 16)
		fj_cell_open_vert_0    = 186 + (74 << 16)
		fj_cell_open_vert_1    = 186 + (75 << 16)
		fj_cell_open_vert_2    = 187 + (75 << 16)
		fj_cell_open_vert_3    = 188 + (75 << 16)
		fj_cell_closed_vert_0  = 186 + (72 << 16)
		fj_cell_closed_vert_1  = 186 + (73 << 16)
		fj_cell_closed_vert_2  = 186 + (74 << 16)
		STR_VAR
		fj_travel_trigger      = bggo_Door0014
		fj_structure_type      = door
		fj_name                = EVAL ~%existing_door_name%~
		fj_door_wed_id         = DOOR02
		fj_door_script		   = EVAL ~%door_script%~
	END
END


/////////////////////////////////////////////////////////
// Door Object 13 is connected to Door0016
/////////////////////////////////////////////////////////

LPF Door_trigger_script_patch 
STR_VAR
	door_name_wed	 	= DOOR01
	door_name			= ~Door0016~
RET
	travel_trigger_found
	bggo_deleted
	existing_door_name
	door_script
END

PATCH_IF bggo_deleted = 1 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_flags               = BIT6 //BIT6 is door
		fj_open_box_left       = 2983
		fj_open_box_top        = 867
		fj_open_box_right      = 3018
		fj_open_box_bottom     = 924
		fj_closed_box_left     = 2976
		fj_closed_box_top      = 837
		fj_closed_box_right    = 2989
		fj_closed_box_bottom   = 917
		fj_cursor_idx          = 30
		fj_open_loc_x          = 3030
		fj_open_loc_y          = 922
		fj_closed_loc_x        = 3030
		fj_closed_loc_y        = 922
		fj_door_open_vert_0    = 2983 + (918 << 16)
		fj_door_open_vert_1    = 3018 + (924 << 16)
		fj_door_open_vert_2    = 3018 + (873 << 16)
		fj_door_open_vert_3    = 2983 + (867 << 16)
		fj_door_closed_vert_0  = 2981 + (917 << 16)
		fj_door_closed_vert_1  = 2989 + (884 << 16)
		fj_door_closed_vert_2  = 2985 + (837 << 16)
		fj_door_closed_vert_3  = 2976 + (872 << 16)
		fj_cell_open_vert_0    = 189 + (100 << 16)
		fj_cell_open_vert_1    = 190 + (100 << 16)
		fj_cell_open_vert_2    = 191 + (100 << 16)
		fj_cell_closed_vert_0  = 189 + (100 << 16)
		fj_cell_closed_vert_1  = 189 + (99 << 16)
		fj_cell_closed_vert_0  = 189 + (98 << 16)
		fj_cell_closed_vert_1  = 189 + (97 << 16)
		fj_cell_closed_vert_0  = 189 + (96 << 16)


		STR_VAR
		fj_travel_trigger      = bggo_Door0016
		fj_structure_type      = door
		fj_name                = EVAL ~%existing_door_name%~
		fj_door_wed_id         = DOOR01
		fj_door_script		   = EVAL ~%door_script%~
	END
END

/////////////////////////////////////////////////////////
// Door Object 15 unused Door04
/////////////////////////////////////////////////////////

LPF Door_trigger_script_patch 
STR_VAR
	door_name_wed	 	= DOOR04
	door_name			= ~Door04~
RET
	travel_trigger_found
	bggo_deleted
	existing_door_name
	door_script
END

PATCH_IF bggo_deleted = 1 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_flags               = BIT6 + BIT7 //BIT6 is door + BIT7 secret
		fj_open_box_left       = 159
		fj_open_box_top        = 2255
		fj_open_box_right      = 200
		fj_open_box_bottom     = 2344
		fj_closed_box_left     = 160
		fj_closed_box_top      = 2227
		fj_closed_box_right    = 198
		fj_closed_box_bottom   = 2312
		fj_cursor_idx          = 30
		fj_open_loc_x          = 206
		fj_open_loc_y          = 2320
		fj_closed_loc_x        = 206
		fj_closed_loc_y        = 2320
		fj_detect_diff 		   = 0xffff
		fj_door_open_vert_0    = 159 + (2324 << 16)
		fj_door_open_vert_1    = 200 + (2344 << 16)
		fj_door_open_vert_2    = 200 + (2278 << 16)
		fj_door_open_vert_3    = 159 + (2255 << 16)
		fj_door_closed_vert_0  = 160 + (2312 << 16)
		fj_door_closed_vert_1  = 198 + (2283 << 16)
		fj_door_closed_vert_2  = 198 + (2227 << 16)
		fj_door_closed_vert_3  = 160 + (2254 << 16)
		fj_cell_open_vert_0    = 10 + (194 << 16)
		fj_cell_open_vert_1    = 11 + (194 << 16)
		fj_cell_open_vert_2    = 12 + (194 << 16)
		fj_cell_open_vert_3    = 12 + (195 << 16)
		fj_cell_closed_vert_0  = 10 + (192 << 16)
		fj_cell_closed_vert_1  = 10 + (191 << 16)
		fj_cell_closed_vert_2  = 11 + (191 << 16)
		fj_cell_closed_vert_3  = 11 + (190 << 16)
		fj_cell_closed_vert_4  = 12 + (190 << 16)
		fj_cell_closed_vert_5  = 12 + (189 << 16)
		STR_VAR
		fj_structure_type      = door
		fj_name                = EVAL ~%existing_door_name%~
		fj_door_wed_id         = DOOR04
		fj_door_script		   = EVAL ~%door_script%~
	END
END

// map note Oberons Estate	
INNER_ACTION BEGIN
	COPY_EXISTING - ~%CentralBaldursGate%.are~ ~override~
		GET_OFFSET_ARRAY mapnotes 0xc4 4 0xc8 4 0 0 0x34
		SET dialog_string = 0
		PHP_EACH mapnotes AS i => off BEGIN
			READ_SHORT off x_coord
			READ_SHORT off + 0x02 y_coord
			PATCH_IF x_coord = 3446 AND y_coord = 176 BEGIN
				READ_LONG off + 0x04 dialog_string
			END
		END
END

PATCH_IF dialog_string > 0 BEGIN
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = 3346
		fj_loc_y = 3127
		fj_note_strref = ~%dialog_string%~
	STR_VAR
		fj_structure_type   = note
	END
END

/////////////////////////////////////////////////////////
// Code for the unused doors
/////////////////////////////////////////////////////////
/*
// Door04

	GET_OFFSET_ARRAY doors ARE_V10_DOORS
	PHP_EACH doors AS i => off BEGIN
		READ_ASCII off + 0x20 door_id
		PATCH_IF ~%door_id%~ STR_EQ ~Door04~ BEGIN
			WRITE_LONG off + 0x28 BIT6 // + BIT1 				//BIT1 is for locked if necessary
			WRITE_SHORT off + 0x8c 0							//lock difficulty			
			WRITE_SHORT off + 0x88 0							
			READ_ASCII off doorname (32) NULL
			WRITE_ASCIIE off + 0x9c ~bggo_%doorname%~ #32
		END
	END
	
	GET_OFFSET_ARRAY triggers ARE_V10_REGIONS
	PHP_EACH triggers AS i => off BEGIN
		READ_ASCII off triggername (32) NULL
		READ_SHORT off + 0x22 xmin
		READ_SHORT off + 0x24 ymin
		PATCH_IF ~%triggername%~ STR_EQ ~InfoHouse~ AND xmin = 162 AND ymin = 2225 BEGIN
			WRITE_ASCIIE off ~bggo_%doorname%~ #32
			WRITE_SHORT off + 0x20 2
			WRITE_SHORT off + 0x34 30
			WRITE_ASCII off + 0x38 ~???~						// destination_area
			WRITE_ASCII off + 0x40 ~???~					// destination_name - exit
			WRITE_LONG off + 0x60 BIT11
			WRITE_LONG off + 0x64 `0
		END
	END
	
	LPF fj_are_structure
		INT_VAR
		fj_loc_x       = 212
		fj_loc_y       = 2319
		fj_orientation = 13
		STR_VAR
		fj_structure_type = entrance
		fj_name           = ExitDoor04								// Exit Name
	END
*/
