//////////////////////////////////////
// identical maps: BG0167
// BG0008 BG0010 BG0157 BG0167 BG0302 BG0619 BG0707 BG0713 BG0805 BG1107 BG1205 BG1209 BG1314 BG3309 BG3311 BG3323 BG3329 BG3333 BG3347 BG3355
//////////////////////////////////////

SPRINT identical_area "BG0167"

PATCH_IF FILE_EXISTS ~%MOD_FOLDER%/base/are_patch/%identical_area%_are.tpa~ BEGIN // add animation for braziers, candles ...
	PATCH_INCLUDE ~%MOD_FOLDER%/base/are_patch/%identical_area%_are.tpa~
END

////////////////////////////////////////////
// trigger to leave to BG1100
////////////////////////////////////////////
LPF fj_are_structure
    INT_VAR
    fj_type         = 2    //travel
    fj_box_left     = 410
    fj_box_top      = 339
    fj_box_right    = 544
    fj_box_bottom   = 449
	fj_flags        = BIT8 //BIT8 deativated
    fj_cursor_idx   = 30   //door
	fj_vertex_0  = 489 + (339 << 16)
	fj_vertex_1  = 410 + (376 << 16)
	fj_vertex_2  = 454 + (449 << 16)
	fj_vertex_3  = 544 + (406 << 16)
    STR_VAR
    fj_structure_type   = region
    fj_name             = bggo_BG1100
    fj_destination_area = EVAL ~%SWBaldursGate%~
    fj_destination_name = Exit0619
END

LPF CreateHouseAreaScript
	STR_VAR
		area_name_house 	= EVAL ~%WBaldursGate_FentensHouse_L1%~
		area_name_1 		= EVAL ~%WBaldursGate%~
		area_name_2 		= EVAL ~%SWBaldursGate%~
END
