//////////////////////////////////////
// identical maps: BG0720
// BG0720 BG1215
//////////////////////////////////////

//Add candles and torches
PATCH_DEFINE_ARRAY x_coord BEGIN 126 261 399 574 701 701 END
PATCH_DEFINE_ARRAY y_coord BEGIN 452 358 259 274 362 91  END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule =  0b111111111111111111111111 //Hours 0.00 - 24.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLMS
		fj_bam_resref = FLMS //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 263 374 409 490 510 617 END
PATCH_DEFINE_ARRAY y_coord BEGIN 504 431 610 515 391 435 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule =  0b111111111111111111111111 //Hours 0.00 - 24.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLAME2N
		fj_bam_resref = FLAME2N //bgrd
	END
END
LPM ~CLEAR_ARRAY~

// two exits to BG0700 *
SNPRINT "-4" exitvar ~%CentralBaldursGate_DrakonTavern%~ //BG0720
SNPRINT "-4" CmpAreaNumDest ~%CentralBaldursGate%~ //BG0700
GET_OFFSET_ARRAY triggers ARE_V10_REGIONS
PHP_EACH triggers AS i => off BEGIN
	READ_ASCII off triggername (32) NULL
	READ_ASCII off + 0x40 entrance (32) NULL
	PATCH_IF ~%triggername%~ STR_EQ ~Door%CmpAreaNumDest%~ AND ~%entrance%~ STR_EQ ~Exit%exitvar%a~ BEGIN
		WRITE_ASCII off + 0x7c ~Dr0720a~
	END
	PATCH_IF ~%triggername%~ STR_EQ ~Door%CmpAreaNumDest%~ AND ~%entrance%~ STR_EQ ~Exit%exitvar%b~ BEGIN
		WRITE_ASCII off + 0x7c ~Dr0720b~
	END
END