//////////////////////////////////////
// identical maps: BG0162
// BG0161 BG0162 BG1111 BG0719 BG1001
//////////////////////////////////////

SPRINT identical_area "BG0162"

PATCH_IF FILE_EXISTS ~%MOD_FOLDER%/base/are_patch/%identical_area%_are.tpa~ BEGIN // add animation for braziers, candles ...
	PATCH_INCLUDE ~%MOD_FOLDER%/base/are_patch/%identical_area%_are.tpa~
END

// two exits to BG0700 *
SNPRINT "-4" exitvar ~%CentralBaldursGate_FeloniusManor%~ //BG0719
SNPRINT "-4" CmpAreaNumDest ~%CentralBaldursGate%~ //BG0700
GET_OFFSET_ARRAY triggers ARE_V10_REGIONS
PHP_EACH triggers AS i => off BEGIN
	READ_ASCII off triggername (32) NULL
	READ_ASCII off + 0x40 entrance (32) NULL
	PATCH_IF ~%triggername%~ STR_EQ ~Door%CmpAreaNumDest%~ AND ~%entrance%~ STR_EQ ~Exit%exitvar%a~ BEGIN
		WRITE_ASCII off + 0x7c ~Dr0719a~
	END
	PATCH_IF ~%triggername%~ STR_EQ ~Door%CmpAreaNumDest%~ AND ~%entrance%~ STR_EQ ~Exit%exitvar%b~ BEGIN
		WRITE_ASCII off + 0x7c ~Dr0719b~
	END
END
