//**************************************************
// Add some braziers in Baldur's Gate
//**************************************************

PATCH_DEFINE_ARRAY x_coord BEGIN 3311 3335 3422 852 714 585 163 3670 3722 END
PATCH_DEFINE_ARRAY y_coord BEGIN 2614 2392 295  43  205 447 822 1203 1329 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = Brazier
		fj_bam_resref = fire_3
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 31  185 2834 2899 3000 1770 1598 1089 1841 1408 1479 1681 1757 2194 2278 559  502  200  128   END
PATCH_DEFINE_ARRAY y_coord BEGIN 693 544 838  946  982  3293 3166 2890 2365 1211 1230 1155 1175 1213 851  2478 2505 2585 2680  END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLAME2N
		fj_bam_resref = FLAME2N //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 1691 1766  END
PATCH_DEFINE_ARRAY y_coord BEGIN 1141 1159  END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		fj_transparent = 220
		STR_VAR
		fj_structure_type = animation
		fj_name = FLAME2N
		fj_bam_resref = FLAME2N //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN  3159  END
PATCH_DEFINE_ARRAY y_coord BEGIN  979   END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLMS
		fj_bam_resref = FLMS //bgrd
	END
END
LPM ~CLEAR_ARRAY~

//////////////////////////////
// Door0805 from BG1300
//////////////////////////////

// Rename the triggers to avoid confusion
LPF CreateTriggerScriptBggodest
STR_VAR
	script_name = dest0805
	area_name = EVAL ~%EBaldursGate_ArkionsHouse_L1%~
RET
	script_name
END

LPF Door_trigger_script_patch
STR_VAR
	door_name		 = Door0805
	new_trigger_name = bggo_BG0805
	trigger_script	 = EVAL ~%script_name%~
END

LPF CreateAreaTravelScript
	INT_VAR
		bggo_locked	   = 1
	STR_VAR
		from_area 	   = EVAL ~%EBaldursGate%~
		to_area   	   = EVAL ~%SEBaldursGate%~
		door_name_from = Door0805
END


//////////////////////////////
// Door0813 from BG1300
//////////////////////////////

// Rename the door to avoid confusion
GET_OFFSET_ARRAY doors ARE_V10_DOORS
PHP_EACH doors AS i => off BEGIN
	READ_ASCII off doorname (32) NULL
	PATCH_IF ~%doorname%~ STR_EQ ~Door Object 11~ BEGIN
		WRITE_ASCII off ~Door0813~ #32
	END
END

LPF CreateAreaTravelScript
	INT_VAR
		bggo_locked	   = 0
	STR_VAR
		from_area 	   = EVAL ~%EBaldursGate%~
		to_area   	   = EVAL ~%SEBaldursGate%~
		door_name_from = Door0813
END


////////////////////////////////////////////////////////////
//  Door0705  The flame to the left of the double door is hidden by the open door.
////////////////////////////////////////////////////////////

PATCH_DEFINE_ARRAY x_coord BEGIN 1777 END
PATCH_DEFINE_ARRAY y_coord BEGIN 2339 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		fj_transparent = 0
		STR_VAR
		fj_structure_type = animation
		fj_name = FlmDoor0705
		fj_bam_resref = FLAME2N //bgrd
	END
END
LPM ~CLEAR_ARRAY~

// Create the doorscript for animations
LPF CreateDoorScriptPatchAnimation
STR_VAR
	animation_name   = FlmDoor0705
	door_name   	 = Door0705
END

// Rename the triggers to avoid confusion add door script
LPF Door_trigger_script_patch
STR_VAR
	door_name		 = Door0705
	new_trigger_name = bggo_BG0705
	door_script		 = Door0705
END

