//**************************************************
// Add some braziers in Baldur's Gate
//**************************************************

PATCH_DEFINE_ARRAY x_coord BEGIN 490  729  1100 1171 294 453 2679 3069 3267 3552 3933 3974 4192 /*4313*/ 3510 3471 3267 3230 1474 1332 1114 862  764  100  88   3551 3466 3395 END
PATCH_DEFINE_ARRAY y_coord BEGIN 1523 1364 1216 1185 549 516 516  869  1151 1505 1602 1644 1861 /*459 */ 3060 3003 2874 2826 2242 2410 2318 2392 2509 2828 2890 636  678  564  END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLAME2N
		fj_bam_resref = FLAME2N //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 3043 2373 2176 1431 764  4078 END
PATCH_DEFINE_ARRAY y_coord BEGIN 2231 1064 1092 1672 2941 3108 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLAME2M
		fj_bam_resref = FLAME2M //bgrd
	END
END
LPM ~CLEAR_ARRAY~

PATCH_DEFINE_ARRAY x_coord BEGIN 3042 END
PATCH_DEFINE_ARRAY y_coord BEGIN 2924 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLMS
		fj_bam_resref = FLMS //bgrd
	END
END
LPM ~CLEAR_ARRAY~

//////////////////////////////////////////////////////////////
// Door01 is visible in both BG1200 and BG1300.
// For this reason, the shared trigger and door are renamed BG1200BG1300.
// The door is now functional for future projects, but it can only be opened once 
// the door flag has been changed from secret door to normal and a destination area has been specified.
// The trigger can then be deactivated (via script or installation).
// The door will function via a script so that when it is opened in BG1200, 
// it is also open in BG1300 and the other way around. 
///////////////////////////////////////////////////////////////

// Rename the triggers to avoid confusion
GET_OFFSET_ARRAY triggers ARE_V10_REGIONS
PHP_EACH triggers AS i => off BEGIN
	READ_ASCII off triggername (32) NULL
	READ_SHORT off + 0x22 bound_left
	PATCH_IF ~%triggername%~ STR_EQ ~InfoHouse~ AND bound_left = 4279 BEGIN
		WRITE_ASCII off ~bggo_door01_trigger~ #32
	END
END

// Add door

LPF Door_trigger_script_patch
STR_VAR
	door_name_wed	 	= DOOR01
RET
	bggo_deleted
END

LPF CreateAreaTravelScript
	STR_VAR
		from_area 	   = EVAL ~%BaldursGateDocks%~
		to_area   	   = EVAL ~%SEBaldursGate%~
		door_name 	   = Door01
END

LPF fj_are_structure
    INT_VAR
    fj_loc_x       = 4247
    fj_loc_y       = 541
    fj_orientation = 2
    STR_VAR
    fj_structure_type = entrance
    fj_name           = bggo_Door01_exit
 END

PATCH_IF bggo_deleted = 1 BEGIN
	GET_OFFSET_ARRAY doors ARE_V10_DOORS
	PHP_EACH doors AS i => off BEGIN
		READ_ASCII off doorname (32) NULL
		PATCH_IF ~%doorname%~ STR_EQ ~Door01~ BEGIN
			LPF fj_are_structure
				INT_VAR fj_delete_mode = i
				STR_VAR fj_structure_type = door
			END 
		END
	END
	
	LPF fj_are_structure
		INT_VAR
		fj_flags               = 0b010000000
		fj_open_box_left       = 4236
		fj_open_box_top        = 420
		fj_open_box_right      = 4284
		fj_open_box_bottom     = 505
		fj_closed_box_left     = 4279
		fj_closed_box_top      = 419
		fj_closed_box_right    = 4314
		fj_closed_box_bottom   = 506
		fj_cursor_idx          = 30
		fj_open_loc_x          = 4247
		fj_open_loc_y          = 541
		fj_closed_loc_x        = 4247
		fj_closed_loc_y        = 541
		fj_detect_diff 		   = 0xffff
		fj_door_open_vert_0    = 4236 + (505 << 16)
		fj_door_open_vert_1    = 4284 + (488 << 16)
		fj_door_open_vert_2    = 4284 + (420 << 16)
		fj_door_open_vert_3    = 4236 + (433 << 16)
		fj_door_closed_vert_0  = 4279 + (479 << 16)
		fj_door_closed_vert_1  = 4314 + (506 << 16)
		fj_door_closed_vert_2  = 4314 + (449 << 16)
		fj_door_closed_vert_3  = 4279 + (419 << 16)
		fj_cell_open_vert_0    = 265 + (40 << 16)
		fj_cell_open_vert_1    = 265 + (41 << 16)
		fj_cell_open_vert_2    = 266 + (40 << 16)
		fj_cell_open_vert_3    = 266 + (41 << 16)
		fj_cell_open_vert_4    = 267 + (39 << 16)
		fj_cell_open_vert_5    = 267 + (40 << 16)
		fj_cell_closed_vert_0  = 267 + (39 << 16)
		fj_cell_closed_vert_1  = 268 + (40 << 16)
		fj_cell_closed_vert_2  = 269 + (40 << 16)
		fj_cell_closed_vert_3  = 269 + (41 << 16)
		STR_VAR
		fj_structure_type      = door
		fj_name                = Door01
		fj_door_wed_id         = DOOR01
	END
END
