//**************************************************
// Add some braziers in Baldur's Gate
//**************************************************

PATCH_DEFINE_ARRAY x_coord BEGIN 791  1368 1427 1305 1704 1760 195  802  847  992  1037 949  1031 1657 1712 790  1305 1369 1427 1704 1760 2158 2113 1772 1601 /*36 */ 512  457  END
PATCH_DEFINE_ARRAY y_coord BEGIN 1179 1190 1157 1391 1079 1047 2348 2561 2527 2417 2384 2688 2778 2298 2310 1179 1391 1191 1157 1078 1047 391  365  223  96   /*443*/ 1804 1832 END
PATCH_PHP_EACH x_coord AS index => x BEGIN
	LPM ~DELETE_EXISTING_ANIMATIONS~
	LPF fj_are_structure
	INT_VAR
		fj_loc_x = $x_coord("%index%")
		fj_loc_y = $y_coord("%index%")
		fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
		fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
		STR_VAR
		fj_structure_type = animation
		fj_name = FLAME2N
		fj_bam_resref = FLAME2N //bgrd
	END
END
LPM ~CLEAR_ARRAY~

//////////////////////////////
// Add actor, who sits in BG1200 at this position
//////////////////////////////
LPF fj_are_structure
    INT_VAR
    fj_loc_x          = 59
    fj_loc_y          = 608
    fj_dest_x         = 59
    fj_dest_y         = 608
    fj_animation      = 0x4100
    fj_orientation    = 2     //SW
	fj_schedule       = 0b000111111111111111110000
    STR_VAR
    fj_structure_type = actor
    fj_name           = "Male Townsfolk"
    fj_cre_resref     = MTOWBASC
  END


//////////////////////////////
// Door0813 from BG0800
//////////////////////////////
LPF Door_trigger_script_patch
STR_VAR
	door_name		 = Door0813
	new_trigger_name = bggo_BG0813
	door_script		 = dr081313
	area_name_dest   = BG0813
END

//////////////////////////////
// Door0805 from BG0800
//////////////////////////////

LPF CreateTriggerScriptBggodest
STR_VAR
	trigger_script = dest0805
	area_name_dest = BG0805 
RET
	trigger_script
	area_name_dest
END

LPF Door_trigger_script_patch
INT_VAR
	bggo_locked 		  = 1	// is door locked =1 unlocked =0
STR_VAR
	door_name_wed	 	= DOOR0805
	door_name			= Door0805
	area_name			= EVAL ~%SEBaldursGate%~
	new_trigger_name	= bggo_BG0805
	trigger_script   	= EVAL ~%trigger_script%~
	door_script			= dr080513
	area_name_dest		= EVAL ~%area_name_dest%~
RET
	travel_trigger_found
	bggo_deleted
	existing_door_name
	door_script
END

// Install only, if the door is not working or found
PATCH_IF bggo_deleted = 1 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_flags               = BIT1 + BIT6 //BIT1 locked BIT6 is door
		fj_open_box_left       = 1527
		fj_open_box_top        = 75
		fj_open_box_right      = 1573
		fj_open_box_bottom     = 142
		fj_closed_box_left     = 1566
		fj_closed_box_top      = 77
		fj_closed_box_right    = 1607
		fj_closed_box_bottom   = 156
		fj_cursor_idx          = 30
		fj_trap_loc_x		   = 1620
		fj_trap_loc_y		   = 126
		fj_open_loc_x          = 1580
		fj_open_loc_y          = 178
		fj_closed_loc_x        = 1580
		fj_closed_loc_y        = 178
		fj_locked_diff		   = 30
		fj_door_open_vert_0    = 1527 + (142 << 16)
		fj_door_open_vert_1    = 1573 + (135 << 16)
		fj_door_open_vert_2    = 1573 + (82  << 16)
		fj_door_open_vert_3    = 1565 + (76  << 16)
		fj_door_open_vert_4    = 1548 + (75  << 16)
		fj_door_open_vert_5    = 1540 + (78  << 16)
		fj_door_open_vert_6    = 1533 + (82  << 16)
		fj_door_open_vert_7    = 1527 + (89  << 16)
		fj_door_closed_vert_0  = 1566 + (135 << 16)
		fj_door_closed_vert_1  = 1607 + (156 << 16)
		fj_door_closed_vert_2  = 1607 + (104 << 16)
		fj_door_closed_vert_3  = 1602 + (95  << 16)
		fj_door_closed_vert_4  = 1597 + (88  << 16)
		fj_door_closed_vert_5  = 1591 + (82  << 16)
		fj_door_closed_vert_6  = 1584 + (77  << 16)
		fj_door_closed_vert_7  = 1576 + (77  << 16)
		fj_door_closed_vert_8  = 1570 + (80  << 16)
		fj_door_closed_vert_9  = 1566 + (83  << 16)
		fj_cell_open_vert_0    = 97 + (11 << 16)
		fj_cell_open_vert_1    = 95 + (11 << 16)
		fj_cell_closed_vert_0  = 54 + (11 << 16)
		fj_cell_closed_vert_1  = 98 + (11 << 16)
		fj_cell_closed_vert_2  = 99 + (11 << 16)
		fj_cell_closed_vert_3  = 99 + (12 << 16)
		fj_cell_closed_vert_4  = 10 + (12 << 16)
		STR_VAR
		fj_travel_trigger      = bggo_BG0805
		fj_structure_type      = door
		fj_name                = EVAL ~%existing_door_name%~
		fj_door_wed_id         = DOOR0805
		fj_door_script		   = EVAL ~%door_script%~
	END
END

PATCH_IF travel_trigger_found = 0 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_type         = 2    //travel
		fj_box_left     = 1566
		fj_box_top      = 77
		fj_box_right    = 1607
		fj_box_bottom   = 156
		fj_cursor_idx   = 30   //door
		fj_flags        = BIT11  //BIT11 door connected
		fj_vertex_0  = 1566 + (135 << 16)
		fj_vertex_1  = 1607 + (156 << 16)
		fj_vertex_2  = 1607 + (104 << 16)
		fj_vertex_3  = 1602 + (95  << 16)
		fj_vertex_4  = 1597 + (88  << 16)
		fj_vertex_5  = 1591 + (82  << 16)
		fj_vertex_6  = 1584 + (77  << 16)
		fj_vertex_7  = 1576 + (77  << 16)
		fj_vertex_8  = 1570 + (80  << 16)
		fj_vertex_9  = 1566 + (83  << 16)
		STR_VAR
		fj_structure_type   = region
		fj_name             = bggo_BG0805
		fj_destination_area = EVAL ~%EBaldursGate_ArkionsHouse_L1%~
		fj_destination_name = Exit0800
		fj_reg_script       = EVAL ~%trigger_script%~
	END
	
	LPF fj_are_structure
		INT_VAR
		fj_loc_x       = 1561
		fj_loc_y       = 173
		fj_orientation = 3
		STR_VAR
		fj_structure_type = entrance
		fj_name           = Exit0805
	END
END


//////////////////////////////////////////////////////////////
// Compatibility with Baldurans Sea Tower Mod Door01 is now used
// 
// Door01 is visible in both BG1200 and BG1300.
// 
// The trigger can then be deactivated (via script or installation).
// The door will function via a script so that when it is opened in BG1200, 
// it is also open in BG1300 and the other way around. 
///////////////////////////////////////////////////////////////

// from BG1200
// Rename the triggers to avoid confusion
GET_OFFSET_ARRAY triggers ARE_V10_REGIONS
PHP_EACH triggers AS i => off BEGIN
	READ_ASCII off triggername (32) NULL
	READ_SHORT off + 0x22 bound_left
	PATCH_IF ~%triggername%~ STR_EQ ~InfoHouse~ AND bound_left = 0 BEGIN
		WRITE_ASCII off ~bggo_InfoHouse~ #32
	END
END


// Add door
LPF CreateTriggerScriptBggodest
STR_VAR
	trigger_script = dest01xx
	area_name_dest = BG01xx // used vor variable name, so we don't need cmpvars
RET
	trigger_script
	area_name_dest
END

LPF Door_trigger_script_patch
STR_VAR
	door_name_wed	 	= DOOR01
	door_name			= Door01
	area_name			= EVAL ~%BaldursGateDocks%~
	new_trigger_name	= bggo_door01
	trigger_script   	= EVAL ~%trigger_script%~
	door_script			= dr01xx13
	area_name_dest		= EVAL ~%area_name_dest%~
RET
	travel_trigger_found
	bggo_deleted
	existing_door_name
	door_script
END

PATCH_IF bggo_deleted = 1 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_flags               = BIT6 + BIT7 //BIT7 secret door BIT6 is door
		fj_open_box_left       = 0
		fj_open_box_top        = 405
		fj_open_box_right      = 5
		fj_open_box_bottom     = 465
		fj_closed_box_left     = 4
		fj_closed_box_top      = 405
		fj_closed_box_right    = 36
		fj_closed_box_bottom   = 492
		fj_cursor_idx          = 30
		fj_open_loc_x          = 25
		fj_open_loc_y          = 505
		fj_closed_loc_x        = 25
		fj_closed_loc_y        = 505
		fj_detect_diff 		   = 0xffff
		fj_door_open_vert_0    = 0 + (465 << 16)
		fj_door_open_vert_1    = 5 + (465 << 16)
		fj_door_open_vert_2    = 5 + (405 << 16)
		fj_door_open_vert_3    = 0 + (405 << 16)
		fj_door_closed_vert_0  = 4  + (468 << 16)
		fj_door_closed_vert_1  = 36 + (492 << 16)
		fj_door_closed_vert_2  = 36 + (429 << 16)
		fj_door_closed_vert_3  = 4  + (405 << 16)
		STR_VAR
		fj_travel_trigger      = bggo_Door01
		fj_structure_type      = door
		fj_name                = EVAL ~%existing_door_name%~
		fj_door_wed_id         = DOOR1300
		fj_door_script		   = EVAL ~%door_script%~
	END
	
END

PATCH_IF travel_trigger_found = 0 BEGIN
	LPF fj_are_structure
		INT_VAR
		fj_type         = 2    //travel
		fj_box_left     = 4
		fj_box_top      = 405
		fj_box_right    = 36
		fj_box_bottom   = 492
		fj_cursor_idx   = 30   //door
		fj_alt_x		= 22
		fj_alt_y		= 508
		fj_flags        = BIT8 + BIT10 + BIT11  //BIT8 deactivated BIT10 activation point BIT11 door connected
		fj_vertex_0     = 4  + (468 << 16)
		fj_vertex_1     = 36 + (492 << 16)
		fj_vertex_2     = 36 + (429 << 16)
		fj_vertex_3     = 4  + (405 << 16)
		STR_VAR
		fj_structure_type   = region
		fj_name             = bggo_Door01
		fj_destination_area = EVAL ~%area_name_dest%~
		fj_destination_name = exit_bg01xx
		fj_reg_script       = EVAL ~%trigger_script%~
	END
	
	LPF fj_are_structure
		INT_VAR
		fj_loc_x       = 11
		fj_loc_y       = 495
		fj_orientation = 0
		STR_VAR
		fj_structure_type = entrance
		fj_name           = bggo_Door01_exit
	END
END

